### ISSUE TITLE
Beautification of offline verifier

### ISSUE THREAD

**Issue by FantasticoFox** [inblockio/aqua-verifier-webextension#48]
![image](https://user-images.githubusercontent.com/45313235/148668371-5c42f46a-066c-4954-b23f-d5fac46340b4.png)

Considerations:
- Drag & Drop into an upload windows
- Start automatic verification and show results

**Comment by lobogang** [comment]
can we close this one? I think @rht implemented this already. If there are further UX requirements we can keep this ticket open and add them here?

**Comment by rht** [comment]
Yeah, let's keep the issue scope small, and close it.
